name: Deploy Trading Bot to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies and package Lambda function
      - name: Install dependencies and package Lambda
        run: |
          pip install -r lambda/requirements.txt -t lambda/
          cd lambda && zip -r ../trading-bot.zip . && cd ..

      # Upload the ZIP file to S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws s3 cp trading-bot.zip s3://trading-bot-bucket/trading-bot.zip

      # Deploy Lambda function
      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name TradingBotFunction \
            --s3-bucket trading-bot-bucket \
            --s3-key trading-bot.zip
